---
- name: Enable start at boot
  template:
    src: acm.service.j2
    dest: /lib/systemd/system/acm.service
    mode: "0644"
  become: true
  when: start_at_boot and can_sudo is success

- name: Register acm in systemd
  systemd:
    name: acm
    enabled: true
    daemon_reload: true
  become: true
  when: start_at_boot and can_sudo is success
