---
- name: create docker group
  group:
    name: docker
    gid: 3657
    state: present

- include: "{{ ansible_os_family }}.yml"

- name: install pip docker
  pip:
    name:
      - pip
      - docker==5.0.3
      - requests==2.27.1
    state: present

- name: Activate Docker API
  replace:
    path: /lib/systemd/system/docker.service
    regexp: 'ExecStart=/usr/bin/dockerd.*$'
    replace: 'ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock -H tcp://0.0.0.0:2375'
  notify: start docker

- name: delete outdated docker-compose
  file:
    path: /usr/bin/docker-compose
    state: absent

- name: Download docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: "0771"
    group: docker

- meta: flush_handlers

- name: fix rights for docker socket
  file:
    path: /var/run/docker.sock
    mode: "0666"
    state: file
  notify: start docker
