---
- name: Add Docker repository
  yum_repository:
    name: docker-ce
    description: Docker CE Stable - $basearch
    baseurl: "https://download.docker.com/linux/centos/{{ ansible_distribution_major_version }}/$basearch/stable"
    gpgkey: https://download.docker.com/linux/centos/gpg
    gpgcheck: true
    state: present
    mode: "0644"

- name: Add CentOS extra repository
  yum_repository:
    name: redhat-extras
    description: CentOS extras repository
    baseurl: "http://mirror.centos.org/centos/{{ ansible_distribution_major_version }}/extras/{{ ansible_architecture }}/"
    state: present
    mode: "0644"
  when: ansible_distribution_major_version|int < 8

- name: Import CentOS key
  rpm_key:
    state: present
    key: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-7
    validate_certs: false
  when: ansible_distribution_major_version|int < 8

- name: install docker
  dnf:
    name:
      - container-selinux
      - "{% if ansible_distribution_major_version|int < 8 %}python-docker-py{% else %}python3-docker{% endif %}"
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-pip
    state: present
    update_cache: true
  notify: start docker
