---
- name: Add a signing key for Kubernetes repo
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
    mode: "0644"

- name: Install kubernetes
  apt:
    name: "{{ item }}={{ k8s_version }}"
    update_cache: true
    state: present
  loop: "{{ k8s_packages }}"