---
- name: change local hostname
  hostname:
    name: "{{ hostname }}.{{ hostname_domain }}"

- name: update /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: "0644"

- name: remove resolvconf package on Debian
  package:
    name: resolvconf
    state: absent

- name: configure systemd-resolved
  copy:
    content: |
      [Resolve]
      Domains={{ hostname_domain }}
    dest: /etc/systemd/resolved.conf
  register: copy_resolved

- name: ensure systemd-resolved is started
  systemd:
    name: systemd-resolved
    enabled: true
    state: started
  when: copy_resolved is changed
