---
- name: change local hostname
  hostname:
    name: "{{ hostname }}.{{ hostname_domain }}"

- name: update /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: "0644"

- name: install resolvconf package on Debian
  package:
    name: resolvconf
    state: present

- name: update resolv.conf
  copy:
    content: "search {{ hostname_domain }}"
    dest: /etc/resolvconf/resolv.conf.d/base
  register: upt_resolv

- name: add google DNS if Proxmox
  copy:
    content: nameserver 8.8.8.8
    dest: /etc/resolvconf/resolv.conf.d/tail
  register: upt_resolv_2
  when: ansible_system_vendor == 'QEMU'

- name: update resolv.conf
  command: resolvconf -u
  when: upt_resolv is changed or upt_resolv_2 is changed
