---
- name: change all rights to users group
  file:
    path: "{{ install_dir }}"
    state: directory
    group: users
    recurse: true
  become: true

- name: get neo4j certificates
  find:
    path: "{{ install_dir }}/apps/neo4j/certificates"
    follow: true
  register: neo4j_certs

- name: apply larger rights on certificates
  file:
    path: "{{ item.path }}"
    mode: "0440"
    state: file
  loop: "{{ neo4j_certs.files }}"
