---
- name: check architecture
  assert:
    that: ansible_architecture in jdk_architecture_dict
    fail_msg: Architecture not supported

- name: Download and uncompress OpenJDK package in /opt
  unarchive:
    src: "https://api.adoptium.net/v3/binary/version/{{ jdk_version }}/linux/{{ jdk_architecture_dict[ansible_architecture] }}/jdk/hotspot/normal/eclipse?project=jdk"
    dest: /opt
    remote_src: true
    list_files: true
  register: tar_contents
- name: "Create symlink from /opt/{{ tar_contents.files[0] }}/bin/java to /usr/bin/java"
  file:
    src: "/opt/{{ tar_contents.files[0] }}/bin/java"
    dest: /usr/bin/java
    state: link
- name: "Create symlink from /opt/{{ tar_contents.files[0] }} to /opt/jdk{{ jdk_version | regex_replace('^jdk-?(?P<version>[0-9]+).*$', '\\g<version>') }}"
  file:
    src: "/opt/{{ tar_contents.files[0] }}"
    dest: "/opt/jdk{{ jdk_version | regex_replace('^jdk-?(?P<version>[0-9]+).*$', '\\g<version>')  }}"
    state: link
