---
- block:
    - name: Install icinga-powershell-framework module
      win_psmodule:
        name: icinga-powershell-framework
        repository: PSGallery
        state: present

    - name: install Icinga2 Agent
      win_shell: |
            Use-Icinga;
            Start-IcingaAgentInstallWizard -SelfServiceAPIKey '{{ icinga_api_key }}' -UseDirectorSelfService 1 `
            -DirectorUrl 'https://{{ icinga_server }}/icingaweb2/director/' -OverrideDirectorVars 0 `
            -ConvertEndpointIPConfig 1 -EmptyCA 1 -CAFile '' -Ticket '' -EmptyTicket 1 `
            -InstallFrameworkPlugins 0 -InstallFrameworkService 0 -CAEndpoint '{{ icinga_server }}' -RunInstaller;
      args:
        creates: C:\\Program Files\\Icinga2
      notify: commit changes to icinga
      become: false

    - name: check that Icinga2 is started
      win_service:
        name: Icinga2
        state: started
      become: false

    - name: wait for Icinga2 to start
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 5665
        state: started
      delegate_to: localhost
      become: false
  when: ansible_distribution_major_version|int > 6
