---
- name: check if the node is present in Icinga
  uri:
    headers:
      Accept: 'application/json'
    force_basic_auth: true
    url_username: "{{ icingaweb_user }}"
    url_password: "{{ icingaweb_pass }}"
    url: "https://{{ icinga_server }}/icingaweb2/director/host?name={{ node_name }}"
    return_content: true
  register: node_api_get
  failed_when: false
  delegate_to: localhost
  become: false

- name: update group if needed
  uri:
    headers:
      Accept: 'application/json'
    force_basic_auth: true
    url_username: "{{ icingaweb_user }}"
    url_password: "{{ icingaweb_pass }}"
    url: "https://{{ icinga_server }}/icingaweb2/director/host?name={{ node_name }}"
    method: POST
    body_format: json
    body: '{"imports": ["{{ node_template }}"]}'
    status_code: 200
  changed_when: true
  notify: commit changes to icinga
  delegate_to: localhost
  become: false
  when:
    - node_api_get.status == 200
    - node_template not in node_api_get.json.imports
    - update_group|bool

- name: update address if needed
  uri:
    headers:
      Accept: 'application/json'
    force_basic_auth: true
    url_username: "{{ icingaweb_user }}"
    url_password: "{{ icingaweb_pass }}"
    url: "https://{{ icinga_server }}/icingaweb2/director/host?name={{ node_name }}"
    method: POST
    body_format: json
    body: '{"address": "{{ ansible_host }}"}'
    status_code: 200
  changed_when: true
  notify: commit changes to icinga
  delegate_to: localhost
  become: false
  when:
    - node_api_get.status in (200, 304)
    - node_api_get.json.address != ansible_host

- name: Prepare API body
  set_fact:
    body_vars: '"vars.environment": "{{ tag_name|d(node_name) }}"'
  when: tag_index is not defined

- name: Prepare API body
  set_fact:
    body_vars: '"vars.environment": "{{ tag_name|d(node_name) }}", "vars.index": "{{ tag_index }}"'
  when: tag_index is defined

- name: create the node if absent in Icinga
  uri:
    headers:
      Accept: 'application/json'
    force_basic_auth: true
    url_username: "{{ icingaweb_user }}"
    url_password: "{{ icingaweb_pass }}"
    url: "https://{{ icinga_server }}/icingaweb2/director/host"
    method: POST
    body_format: json
    body: '{"address": "{{ ansible_host }}", "imports": {{ node_template.split(",")|list }}, "object_name": "{{ node_name }}", "object_type": "object", {{ body_vars }} }'
    status_code: 201
  changed_when: true
  delegate_to: localhost
  become: false
  ignore_errors: true
  when: node_api_get.status == 404

- name: commit config to finally create the node
  uri:
    headers:
      Accept: 'application/json'
    force_basic_auth: true
    url_username: "{{ icingaweb_user }}"
    url_password: "{{ icingaweb_pass }}"
    url: "https://{{ icinga_server }}/icingaweb2/director/config/deploy"
    method: POST
  changed_when: true
  delegate_to: localhost
  become: false
  when: node_api_get.status == 404
  run_once: true

- include: "install-{{ ansible_os_family }}.yml"
  when: node_api_get.status in (200, 404)
