---
- name: uninstall Icinga2 Agent
  win_shell: |
        Use-Icinga;
        Uninstall-IcingaAgent -RemoveDataFolder;
  args:
    removes: C:\\Program Files\\Icinga2
  notify: commit changes to icinga
  become: false
  when: ansible_distribution_major_version|int > 6
