---
- name: check if the node is present in Icinga
  uri:
    headers:
      Accept: 'application/json'
    force_basic_auth: true
    url_username: "{{ icingaweb_user }}"
    url_password: "{{ icingaweb_pass }}"
    url: "https://{{ icinga_server }}/icingaweb2/director/hosts"
    return_content: true
    body_format: json
  register: env_api_get
  failed_when: false
  delegate_to: localhost
  become: false

- name: delete the hosts relevant to node_name
  uri:
    headers:
      Accept: 'application/json'
    force_basic_auth: true
    url_username: "{{ icingaweb_user }}"
    url_password: "{{ icingaweb_pass }}"
    url: "https://{{ icinga_server }}/icingaweb2/director/host?name={{ item.object_name }}"
    method: DELETE
  notify: commit changes to icinga
  changed_when: true
  delegate_to: localhost
  become: false
  when:
    - env_api_get.status == 200
    - "'vars' in item"
    - "'environment' in item.vars"
    - item.vars.environment == node_name
  loop: "{{ env_api_get.json.objects|d([]) }}"
