---
- name: check is current user has sudo rights
  command: /bin/true
  become: true
  changed_when: false
  ignore_errors: true
  register: can_sudo

- include_tasks: "{{ hs5_service_action }}.yml"
