---
- block:
    - name: check if hs5 is registered
      service_facts:

    - name: Deregister hs5 at startup
      systemd:
        name: hs5
        enabled: false
      become: true
      when: "'hs5.service' in ansible_facts.services"

    - name: Delete hs5 systemd scripts
      file:
        path: /lib/systemd/system/hs5.service
        state: absent
      become: true
  when: can_sudo is success
