---
- block:
    - name: check if acm is registered
      service_facts:

    - name: Deregister acm at startup
      systemd:
        name: acm
        enabled: false
      become: true
      when: "'acm.service' in ansible_facts.services"

    - name: Delete acm systemd scripts
      file:
        path: /lib/systemd/system/acm.service
        state: absent
      become: true
  when: can_sudo is success
