---
- name: check is current user has sudo rights
  command: /bin/true
  become: true
  changed_when: false
  ignore_errors: true
  register: can_sudo
  tags: always

- name: check if profile.sh exists
  stat:
    path: "{{ install_dir }}/apps/bin/env/profile.sh"
  register: st_profile

- name: fetch profile.sh if exists
  fetch:
    src: "{{ install_dir }}/apps/bin/env/profile.sh"
    dest: /tmp/profile.sh
    flat: true
  when: st_profile.stat.exists
  changed_when: false

- name: create profile.sh directories if not exists
  file:
    path: "{{ install_dir }}/apps/bin/env"
    state: directory
    recurse: true
  register: cr_profile_dir
  when: not st_profile.stat.exists
  ignore_errors: true

- name: copy profile.sh if not exists
  copy:
    src: /tmp/profile.sh
    dest: "{{ install_dir }}/apps/bin/env/profile.sh"
    mode: "0644"
  when: not st_profile.stat.exists and cr_profile_dir is not failed

- include_tasks: "{{ ansible_os_family }}.yml"
