---
- name: check that fqdn and email are correctly defined
  assert:
    that: fqdn is defined

- name: install keytool
  package:
    name: openssl
    state: present

- name: create ssl directory
  file:
    path: "{{ ssl_dir }}"
    state: directory
    recurse: true

- name: Generate an OpenSSL private key with the default values
  openssl_privatekey:
    path: "{{ ssl_dir }}/privkey.pem"
    state: present

- name: Generate an OpenSSL Certificate Signing Request
  openssl_csr:
    path: "{{ ssl_dir }}/{{ fqdn }}.csr"
    privatekey_path: "{{ ssl_dir }}/privkey.pem"
    common_name: "{{ fqdn }}"
    email_address: "{{ admin_email }}"
    organization_name: IMTF
    mode: "0644"
    state: present

- name: Generate a Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{ ssl_dir }}/fullchain.pem"
    privatekey_path: "{{ ssl_dir }}/privkey.pem"
    csr_path: "{{ ssl_dir }}/{{ fqdn }}.csr"
    selfsigned_not_after: "+{{ cert_days }}d"
    provider: selfsigned
    mode: "0644"
    state: present
