---
- name: Check the given timezone is valid
  assert:
    that:
      - timezone in timezone_dict
      - ansible_os_family is defined
      - ansible_os_family in ('Debian', 'RedHat', 'Windows')

- include: "{{ ansible_os_family }}.yml"
